keypress("G", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.102, bpm)
keypress("p", x, bpm)
rest(0.108, bpm)
keypress("S", x, bpm)
rest(0.04, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("D", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("s", x, bpm)
keypress("G", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(1.5, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(1.5, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
keypress("6", x, bpm)
rest(0.123, bpm)
keypress("n", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.125, bpm)
keypress("n", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.002, bpm)
keypress("0", x, bpm)
keypress("t", x, bpm)
rest(0.121, bpm)
keypress("n", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.125, bpm)
keypress("n", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.004, bpm)
keypress("0", x, bpm)
keypress("t", x, bpm)
rest(0.119, bpm)
keypress("n", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.125, bpm)
keypress("n", x, bpm)
rest(0.131, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.123, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
rest(0.125, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
rest(0.002, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.121, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
rest(0.125, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
rest(0.004, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.119, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
rest(0.125, bpm)
keypress("b", x, bpm)
rest(0.131, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("C", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
keypress("6", x, bpm)
rest(0.104, bpm)
keypress("0", x, bpm)
rest(0.019, bpm)
keypress("n", x, bpm)
rest(0.09, bpm)
keypress("t", x, bpm)
rest(0.035, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.125, bpm)
keypress("n", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.123, bpm)
keypress("n", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.004, bpm)
keypress("6", x, bpm)
rest(0.121, bpm)
keypress("n", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.004, bpm)
keypress("0", x, bpm)
keypress("t", x, bpm)
rest(0.119, bpm)
keypress("n", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.006, bpm)
keypress("6", x, bpm)
rest(0.119, bpm)
keypress("n", x, bpm)
rest(0.131, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.123, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
rest(0.125, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
rest(0.123, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
rest(0.125, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
rest(0.004, bpm)
keypress("6", x, bpm)
rest(0.119, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
rest(0.125, bpm)
keypress("b", x, bpm)
rest(0.131, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.104, bpm)
keypress("V", x, bpm)
rest(0.146, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.104, bpm)
keypress("V", x, bpm)
rest(0.146, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.104, bpm)
keypress("C", x, bpm)
rest(0.146, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.104, bpm)
keypress("C", x, bpm)
rest(0.146, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.102, bpm)
keypress("p", x, bpm)
rest(0.108, bpm)
keypress("S", x, bpm)
rest(0.04, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("D", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.102, bpm)
keypress("p", x, bpm)
rest(0.108, bpm)
keypress("S", x, bpm)
rest(0.04, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("D", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("s", x, bpm)
keypress("G", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(1.5, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
keypress("6", x, bpm)
rest(0.123, bpm)
keypress("n", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.002, bpm)
keypress("6", x, bpm)
rest(0.123, bpm)
keypress("n", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.002, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.121, bpm)
keypress("n", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.004, bpm)
keypress("8", x, bpm)
rest(0.121, bpm)
keypress("n", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.004, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.119, bpm)
keypress("n", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.006, bpm)
keypress("8", x, bpm)
rest(0.119, bpm)
keypress("n", x, bpm)
rest(0.131, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.123, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
rest(0.002, bpm)
keypress("e", x, bpm)
rest(0.123, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
rest(0.002, bpm)
keypress("t", x, bpm)
rest(0.121, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
rest(0.004, bpm)
keypress("e", x, bpm)
rest(0.121, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
rest(0.004, bpm)
keypress("Q", x, bpm)
rest(0.119, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
rest(0.006, bpm)
keypress("8", x, bpm)
rest(0.119, bpm)
keypress("b", x, bpm)
rest(0.131, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("C", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
keypress("6", x, bpm)
rest(0.104, bpm)
keypress("0", x, bpm)
rest(0.019, bpm)
keypress("n", x, bpm)
rest(0.09, bpm)
keypress("t", x, bpm)
rest(0.035, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.125, bpm)
keypress("n", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.123, bpm)
keypress("n", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.004, bpm)
keypress("6", x, bpm)
rest(0.121, bpm)
keypress("n", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.004, bpm)
keypress("0", x, bpm)
keypress("t", x, bpm)
rest(0.119, bpm)
keypress("n", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.006, bpm)
keypress("6", x, bpm)
rest(0.119, bpm)
keypress("n", x, bpm)
rest(0.131, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.123, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
rest(0.125, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
rest(0.002, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.121, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
rest(0.125, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
rest(0.004, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.119, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
rest(0.125, bpm)
keypress("b", x, bpm)
rest(0.131, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("C", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("6", x, bpm)
rest(0.05, bpm)
keypress("L", x, bpm)
rest(0.054, bpm)
keypress("x", x, bpm)
rest(0.05, bpm)
keypress("V", x, bpm)
rest(0.096, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(4.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
rest(1.5, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("0", x, bpm)
rest(0.104, bpm)
keypress("Q", x, bpm)
rest(0.104, bpm)
keypress("e", x, bpm)
rest(0.108, bpm)
keypress("t", x, bpm)
rest(1.183, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
rest(1.5, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(3, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(3, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(1.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
rest(1.5, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1.5, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
rest(1.5, bpm)
keypress("H", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.05, bpm)
keypress("L", x, bpm)
rest(0.054, bpm)
keypress("x", x, bpm)
rest(0.05, bpm)
keypress("V", x, bpm)
rest(2.846, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(3, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
rest(1.5, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("0", x, bpm)
rest(0.052, bpm)
keypress("Q", x, bpm)
rest(0.052, bpm)
keypress("r", x, bpm)
rest(0.054, bpm)
keypress("t", x, bpm)
rest(1.342, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.05, bpm)
keypress("k", x, bpm)
rest(0.054, bpm)
keypress("x", x, bpm)
rest(0.05, bpm)
keypress("V", x, bpm)
rest(2.846, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(3, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(3, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(3, bpm)
keypress("H", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.104, bpm)
keypress("V", x, bpm)
rest(1.396, bpm)
keypress("f", x, bpm)
rest(0.104, bpm)
keypress("x", x, bpm)
rest(1.396, bpm)
keypress("S", x, bpm)
keypress("O", x, bpm)
rest(0.104, bpm)
keypress("L", x, bpm)
rest(2.896, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.104, bpm)
keypress("V", x, bpm)
rest(1.396, bpm)
keypress("D", x, bpm)
rest(0.104, bpm)
keypress("Z", x, bpm)
rest(1.396, bpm)
keypress("a", x, bpm)
keypress("I", x, bpm)
rest(0.104, bpm)
keypress("k", x, bpm)
rest(2.896, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.104, bpm)
keypress("C", x, bpm)
rest(1.396, bpm)
keypress("d", x, bpm)
rest(0.104, bpm)
keypress("z", x, bpm)
rest(1.396, bpm)
keypress("S", x, bpm)
keypress("I", x, bpm)
rest(0.104, bpm)
keypress("L", x, bpm)
rest(1.396, bpm)
keypress("p", x, bpm)
rest(0.104, bpm)
keypress("j", x, bpm)
rest(1.396, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.104, bpm)
keypress("C", x, bpm)
rest(1.396, bpm)
keypress("d", x, bpm)
rest(0.104, bpm)
keypress("z", x, bpm)
rest(1.396, bpm)
keypress("S", x, bpm)
keypress("O", x, bpm)
rest(0.104, bpm)
keypress("L", x, bpm)
rest(2.896, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.104, bpm)
keypress("x", x, bpm)
rest(1.396, bpm)
keypress("a", x, bpm)
rest(0.104, bpm)
keypress("k", x, bpm)
rest(1.396, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
rest(0.104, bpm)
keypress("x", x, bpm)
rest(1.496, bpm)
keypress("h", x, bpm)
rest(0.104, bpm)
keypress("v", x, bpm)
rest(1.641, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.104, bpm)
keypress("C", x, bpm)
rest(1.176, bpm)
keypress("P", x, bpm)
rest(0.64, bpm)
keypress("T", x, bpm)
rest(0.711, bpm)
keypress("I", x, bpm)
rest(0.711, bpm)
keypress("P", x, bpm)
rest(0.711, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
rest(0.711, bpm)
keypress("S", x, bpm)
rest(0.711, bpm)
keypress("J", x, bpm)
rest(0.711, bpm)
keypress("G", x, bpm)
rest(0.711, bpm)
keypress("L", x, bpm)

finishedSong()