keypress("6", x, bpm)
rest(2, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
rest(2, bpm)
keypress("3", x, bpm)
rest(2, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
rest(1.625, bpm)
keypress("3", x, bpm)
rest(0.125, bpm)
keypress("$", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("6", x, bpm)
rest(2, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
rest(2, bpm)
keypress("3", x, bpm)
rest(2, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
rest(2, bpm)
keypress("6", x, bpm)
keypress("u", x, bpm)
rest(0.875, bpm)
keypress("u", x, bpm)
rest(0.875, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("u", x, bpm)
rest(0.875, bpm)
keypress("u", x, bpm)
rest(0.875, bpm)
keypress("3", x, bpm)
keypress("u", x, bpm)
rest(0.875, bpm)
keypress("u", x, bpm)
rest(0.875, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.875, bpm)
keypress("u", x, bpm)
rest(0.875, bpm)
keypress("6", x, bpm)
keypress("u", x, bpm)
rest(0.875, bpm)
keypress("u", x, bpm)
rest(0.875, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.875, bpm)
keypress("u", x, bpm)
rest(0.875, bpm)
keypress("3", x, bpm)
keypress("u", x, bpm)
rest(0.875, bpm)
keypress("u", x, bpm)
rest(0.875, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.875, bpm)
keypress("u", x, bpm)
rest(0.875, bpm)
keypress("6", x, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("3", x, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(1.5, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("p", x, bpm)
rest(1.5, bpm)
keypress("3", x, bpm)
keypress("s", x, bpm)
rest(1.5, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
rest(1.5, bpm)
keypress("%", x, bpm)
keypress("d", x, bpm)
rest(0.625, bpm)
keypress("d", x, bpm)
rest(0.625, bpm)
keypress("0", x, bpm)
keypress("9", x, bpm)
keypress("d", x, bpm)
rest(0.625, bpm)
keypress("d", x, bpm)
rest(0.625, bpm)
keypress("3", x, bpm)
keypress("d", x, bpm)
rest(0.625, bpm)
keypress("s", x, bpm)
rest(0.625, bpm)
keypress("0", x, bpm)
keypress("9", x, bpm)
keypress("a", x, bpm)
rest(0.625, bpm)
keypress("d", x, bpm)
rest(0.625, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.625, bpm)
keypress("s", x, bpm)
rest(0.625, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
rest(0.625, bpm)
keypress("s", x, bpm)
rest(0.625, bpm)
keypress("s", x, bpm)
keypress("3", x, bpm)
rest(0.625, bpm)
keypress("a", x, bpm)
rest(0.625, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
rest(0.625, bpm)
keypress("s", x, bpm)
rest(0.625, bpm)
keypress("7", x, bpm)
keypress("a", x, bpm)
rest(0.625, bpm)
keypress("a", x, bpm)
rest(0.625, bpm)
keypress("(", x, bpm)
keypress("e", x, bpm)
keypress("a", x, bpm)
rest(0.625, bpm)
keypress("a", x, bpm)
rest(0.625, bpm)
keypress("$", x, bpm)
keypress("I", x, bpm)
rest(1.25, bpm)
keypress("(", x, bpm)
keypress("e", x, bpm)
keypress("a", x, bpm)
rest(1.25, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("0", x, bpm)
rest(2.5, bpm)
keypress("3", x, bpm)
rest(2, bpm)
keypress("$", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("6", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("l", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("z", x, bpm)
rest(0.375, bpm)
keypress("l", x, bpm)
rest(0.375, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("k", x, bpm)
rest(0.375, bpm)
keypress("z", x, bpm)
rest(0.375, bpm)
keypress("8", x, bpm)
keypress("l", x, bpm)
rest(0.375, bpm)
keypress("k", x, bpm)
rest(0.375, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("j", x, bpm)
rest(0.375, bpm)
keypress("l", x, bpm)
rest(0.375, bpm)
keypress("7", x, bpm)
keypress("k", x, bpm)
rest(0.375, bpm)
keypress("j", x, bpm)
rest(0.375, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("H", x, bpm)
rest(0.375, bpm)
keypress("k", x, bpm)
rest(0.375, bpm)
keypress("6", x, bpm)
keypress("j", x, bpm)
rest(0.375, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.625, bpm)
keypress("g", x, bpm)
keypress("3", x, bpm)
rest(0.375, bpm)
keypress("f", x, bpm)
rest(0.375, bpm)
keypress("$", x, bpm)
keypress("d", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
keypress("a", x, bpm)
rest(0.375, bpm)
keypress("p", x, bpm)
rest(0.375, bpm)
keypress("3", x, bpm)
keypress("O", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
rest(0.375, bpm)
keypress("6", x, bpm)
keypress("p", x, bpm)
rest(1.5, bpm)
keypress("3", x, bpm)
rest(1.25, bpm)
keypress("$", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("6", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("9", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("9", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("9", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("7", x, bpm)
rest(0.125, bpm)
keypress("*", x, bpm)
rest(0.125, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("W", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("W", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("W", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("p", x, bpm)
rest(1.5, bpm)
keypress("3", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(0.75, bpm)
keypress("$", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("6", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("9", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("9", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(2.25, bpm)
keypress("6", x, bpm)
rest(2, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(2, bpm)
keypress("3", x, bpm)
rest(2, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(1.625, bpm)
keypress("3", x, bpm)
rest(0.125, bpm)
keypress("$", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("6", x, bpm)
rest(1.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(1.75, bpm)
keypress("3", x, bpm)
rest(1.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(1.5, bpm)
keypress("6", x, bpm)
rest(1.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1.25, bpm)
keypress("3", x, bpm)
rest(1.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.875, bpm)
keypress("3", x, bpm)
rest(0.125, bpm)
keypress("$", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.75, bpm)
keypress("3", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.75, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("3", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("9", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("9", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("x", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("b", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("b", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("b", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("p", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("H", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
keypress("H", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("H", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
keypress("H", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("H", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("x", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("b", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("b", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("V", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("b", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
keypress("j", x, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("B", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("i", x, bpm)
keypress("Z", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("B", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("b", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("B", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
keypress("C", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("J", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("Z", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("B", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("C", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("J", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("Z", x, bpm)
keypress("B", x, bpm)

finishedSong()